# Generated by Django 2.1.2 on 2019-04-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalizedDataBase',
            fields=[
                ('Pno', models.IntegerField(default='0', primary_key=True, serialize=False)),
                ('Caseno', models.IntegerField(default='0')),
                ('Patient_name', models.CharField(default=' ', max_length=20)),
                ('Doctor_name', models.CharField(default=' ', max_length=20)),
                ('dob', models.DateField(default='1998-01-02')),
                ('Entery_date', models.DateField(default='1998-01-02')),
                ('Department', models.CharField(default=' ', max_length=20)),
                ('Remark', models.CharField(default=' ', max_length=20)),
                ('Admitting_date', models.DateField(default='1998-01-02')),
                ('Discharge_Date', models.DateField(default='1998-01-02')),
            ],
        ),
        migrations.CreateModel(
            name='PatientDatabase',
            fields=[
                ('Pno', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('clerk_ID', models.CharField(default=' ', max_length=20)),
                ('description', models.CharField(default=' ', max_length=10)),
                ('Register_Date_time', models.DateField(default=' ')),
                ('HealthCare_no', models.CharField(default=' ', max_length=10)),
                ('first_name', models.CharField(default=' ', max_length=10)),
                ('last_name', models.CharField(default=' ', max_length=10)),
                ('Address', models.CharField(default=' ', max_length=200)),
                ('city', models.CharField(default=' ', max_length=10)),
                ('Registration_Loc', models.CharField(default=' ', max_length=10)),
                ('state', models.CharField(default=' ', max_length=10)),
                ('zip_code', models.CharField(default=' ', max_length=10)),
                ('country', models.CharField(default=' ', max_length=10)),
                ('phone_no_home', models.CharField(default=' ', max_length=10)),
                ('phone_no_work', models.CharField(default=' ', max_length=10)),
                ('email', models.EmailField(default='', max_length=254)),
                ('sex', models.CharField(default=' ', max_length=10)),
                ('dob', models.DateField(default=' ')),
                ('maritial_status', models.CharField(default=' ', max_length=10)),
                ('emer_first_name', models.CharField(default=' ', max_length=100)),
                ('emer_last_name', models.CharField(default=' ', max_length=100)),
                ('relationship', models.CharField(default=' ', max_length=100)),
                ('emer_contact', models.CharField(default=' ', max_length=100)),
                ('blood_pressure', models.CharField(default=' ', max_length=100)),
                ('body_temp', models.CharField(default=' ', max_length=10)),
                ('pulse', models.CharField(default=' ', max_length=10)),
                ('breathing', models.CharField(default=' ', max_length=10)),
            ],
        ),
    ]
