# Generated by Django 2.1.2 on 2019-04-07 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospitalizeddatabase',
            old_name='Pno',
            new_name='Patient_no',
        ),
    ]
