# Generated by Django 2.1.2 on 2019-04-07 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20190407_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdatabase',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patientdatabase',
            name='mode_arrival',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='patientdatabase',
            name='triage',
            field=models.IntegerField(default=0),
        ),
    ]
