# Generated by Django 2.1.2 on 2019-04-07 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20190407_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdatabase',
            name='mode_arrival',
            field=models.TextField(default=' ', max_length=100),
        ),
    ]
