# Generated by Django 2.1.2 on 2019-04-07 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20190407_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdatabase',
            name='blood_pressure',
            field=models.IntegerField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='patientdatabase',
            name='breathing',
            field=models.IntegerField(default=' ', max_length=10),
        ),
        migrations.AlterField(
            model_name='patientdatabase',
            name='pulse',
            field=models.IntegerField(default=' ', max_length=10),
        ),
    ]
