# Generated by Django 2.1.2 on 2019-04-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20190407_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdatabase',
            name='blood_pressure',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patientdatabase',
            name='breathing',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patientdatabase',
            name='pulse',
            field=models.IntegerField(default=0),
        ),
    ]
