# Generated by Django 2.1.2 on 2019-04-09 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_beddatabase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beddatabase',
            name='Deluxe_bed',
        ),
        migrations.RemoveField(
            model_name='beddatabase',
            name='Female_ward',
        ),
        migrations.RemoveField(
            model_name='beddatabase',
            name='General_bed',
        ),
        migrations.RemoveField(
            model_name='beddatabase',
            name='Male_ward',
        ),
        migrations.RemoveField(
            model_name='beddatabase',
            name='Private_bed',
        ),
        migrations.AddField(
            model_name='beddatabase',
            name='Gender_ward',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='beddatabase',
            name='bed_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
