# Generated by Django 2.1.2 on 2019-04-09 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20190409_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalizeddatabase',
            name='bed_alloted',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
