# Generated by Django 2.1.2 on 2019-04-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_hospitalizeddatabase_bed_alloted'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalizeddatabase',
            name='hspt_prcnt',
            field=models.CharField(default=' ', max_length=10),
        ),
        migrations.AddField(
            model_name='hospitalizeddatabase',
            name='not_h_prcnt',
            field=models.CharField(default=' ', max_length=10),
        ),
        migrations.AddField(
            model_name='patientdatabase',
            name='hspt_prcnt',
            field=models.CharField(default=' ', max_length=10),
        ),
        migrations.AddField(
            model_name='patientdatabase',
            name='not_h_prcnt',
            field=models.CharField(default=' ', max_length=10),
        ),
    ]
